<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH9BIxh8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH9BIxh8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH9BIxh8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH9BIxh8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerH9BIxh8\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'H9BIxh8',
    'container.build_id' => '035c8817',
    'container.build_time' => 1618610980,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH9BIxh8');
