<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZsTOZeo\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZsTOZeo/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZsTOZeo.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZsTOZeo\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZsTOZeo\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZsTOZeo',
    'container.build_id' => '38321fac',
    'container.build_time' => 1618408560,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZsTOZeo');
